// angular-animations/src/app/components/item-input/item-input.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder } from '@angular/forms';

import { ApiService } from '@services';

@Component({
  selector: 'app-item-input',
  templateUrl: './item-input.component.html',
  styleUrls: ['./item-input.component.scss'],
})
export class ItemInputComponent implements OnInit {
  @Input() isVisible: boolean;
  @Output() closed = new EventEmitter<boolean>();

  public todoGroup = this.fb.group({
    text: null,
    intervals: null,
  });

  constructor(
    private fb: FormBuilder,
    private apiService: ApiService) {
  }

  ngOnInit() {
  }

  public addTodo() {
    this.apiService.addTodo({
      id: Math.random() % 100,
      date: new Date().toLocaleDateString(),
      ...this.todoGroup.value,
    });

    this.closed.emit(true);
  }
}

<div
  *ngIf="isVisible"
  class="modal-box">
  <div class="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add new todo</h5>
        </div>
        <div class="modal-body">
          <form [formGroup]="todoGroup">
            <div class="inputs">
              <div class="form-group">
              <textarea
                class="form-control todo-text"
                cols="30"
                formControlName="text"
                id="todo-text"
                rows="5"></textarea>
              </div>
              <div class="form-group with-icon">
                <label for="todo-interval"><i class="mdi mdi-timer-sand mr-2"></i>Interval</label>
                <input
                  class="form-control"
                  formControlName="intervals"
                  id="todo-interval"
                  type="number" />
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button
            (click)="addTodo()"
            class="btn btn-primary">
            Add
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="overlay"></div>
</div>

// vue-animations/src/components/ItemInput.vue
<template>
  <div
    v-if="isVisible"
    class="modal-box">
    <div class="modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Add new todo</h5>
          </div>
          <div class="modal-body">
            <div class="inputs">
              <div class="form-group">
              <textarea
                v-model="todoToAddText"
                class="form-control todo-text"
                cols="30"
                id="todo-text"
                rows="5"></textarea>
              </div>
              <div class="form-group with-icon">
                <label for="todo-interval"><i class="mdi mdi-timer-sand mr-2"></i>Interval</label>
                <input
                  type="number"
                  class="form-control"
                  id="todo-interval"
                  v-model="intervalNumber" />
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button
              @click="addTodo"
              class="btn btn-primary">
              Add
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="overlay"></div>
  </div>
</template>

<script>
import Vue from 'vue';
import { Actions } from '@/store';

export default Vue.extend({
  name: 'ItemInput',
  props: {
    isVisible: Boolean,
  },
  data() {
    return {
      todoToAddText: '',
      intervalNumber: 0,
    };
  },
  methods: {
    async addTodo() {
      const todoToAdd = {
        id: Math.random(),
        date: new Date().toLocaleDateString(),
        text: this.todoToAddText,
        interval: this.intervalNumber,
      };

      await this.$store.dispatch(Actions.addTodo, todoToAdd);
      this.$emit('close');
    },
  },
});
</script>

<style lang="scss" scoped>
@import 'components/item-input';
</style>
