// angular-animations/src/app/components/list/list.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from '@models';
import { ApiService } from '@services';

@Component({
  selector: 'app-list',
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss']
})
export class ListComponent implements OnInit {

  constructor(private apiService: ApiService) { }

  public todos: Todo[] = [];
  public selectedTodos: Todo[] = [];

  async ngOnInit() {
    this.todos = await this.apiService.fetchTodos();
  }

  public removeSelected() {
    this.todos = this.todos.filter(t => !this.selectedTodos.includes(t));
    this.apiService.removeTodos(this.selectedTodos);
    this.selectedTodos = [];
  }

  public clickTodoItem(todo: Todo) {
    if (this.selectedTodos.includes(todo)) {
      this.deselectTodo(todo);
    } else {
      this.selectTodo(todo);
    }
  }

  private selectTodo(todo: Todo) {
    this.selectedTodos.push(todo);
  }

  private deselectTodo(todo: Todo) {
    this.selectedTodos = this.selectedTodos.filter(t => t.id !== todo.id);
  }
}

<div *ngIf="selectedTodos.length !== 0" class="header">
  <button
    (click)="removeSelected()"
    class="btn btn-secondary"
    type="button">Delete
  </button>
</div>

<ul class="list-group my-4">
  <li
    *ngFor="let todo of todos"
    (click)="clickTodoItem(todo)"
    [class.selected]="selectedTodos.includes(todo)"
    class="list-group-item">
    {{ todo.text }}
  </li>
</ul>

// vue-animations/src/components/List.vue
<template>
  <div>
    <div v-if="selectedTodos.length !== 0" class="header">
      <button
        @click="removeSelected"
        class="btn btn-secondary"
        type="button">Delete
      </button>
    </div>
    <ul class="list-group my-4">
      <template v-for="todo in todos">
        <ListItem
          :key="todo.id"
          :todo="todo"
          @deselected="deselectTodo"
          @selected="selectTodo" />
      </template>
    </ul>
  </div>
</template>

<script>
import Vue from 'vue';
import { Actions } from '@/store';
import ListItem from './ListItem.vue';

export default Vue.extend({
  name: 'List',
  components: {
    ListItem,
  },
  async created() {
    await this.$store.dispatch(Actions.fetchTodos);
  },
  computed: {
    todos() {
      return this.$store.state.todos;
    },
  },
  data() {
    return {
      selectedTodos: [],
    };
  },
  methods: {
    selectTodo(todo) {
      this.selectedTodos.push(todo);
    },
    deselectTodo(todo) {
      this.selectedTodos = this.selectedTodos.filter(t => t.id !== todo.id);
    },
    removeSelected() {
      this.$store.dispatch(Actions.removeTodos, this.selectedTodos);
      this.selectedTodos = [];
    },
  },
});
</script>

<style lang="scss" scoped>
.header {
  display: flex;
  justify-content: flex-end;
  margin-top: 1rem;
}
</style>
