// angular-animations/src/app/components/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { transition, trigger, useAnimation } from '@angular/animations';

import { slidingCardEnterLeft, slidingCardEnterRight } from '@animations';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  animations: [
    trigger('routeAnimations', [
      transition('DashboardPage => AboutPage', [
        useAnimation(slidingCardEnterLeft),
      ]),
      transition('AboutPage => DashboardPage', [
        useAnimation(slidingCardEnterRight),
      ]),
    ]),
  ],
})
export class AppComponent {
  public prepareRoute(outlet: RouterOutlet) {
    return outlet && outlet.activatedRouteData && outlet.activatedRouteData['animation'];
  }
}

<div class="navbar navbar-expand navbar-dark bg-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a
        class="nav-link"
        routerLink="/">
        Dashboard
      </a>
    </li>
    <li class="nav-item">
      <a
        class="nav-link"
        routerLink="/about">
        About
      </a>
    </li>
  </ul>
</div>

<div [@routeAnimations]="prepareRoute(outlet)">
  <router-outlet #outlet="outlet"></router-outlet>
</div>

// vue-animations/src/App.vue
<template>
  <div id="app">
    <div class="navbar navbar-expand navbar-dark bg-dark">
      <ul class="navbar-nav">
        <li class="nav-item">
          <router-link
            class="nav-link"
            to="/">Dashboard
          </router-link>
        </li>
        <li class="nav-item">
          <router-link
            class="nav-link"
            to="/about">About
          </router-link>
        </li>
      </ul>
    </div>
    <div class="container">
      <router-view />
    </div>
  </div>
</template>

<style lang="scss">
@import 'styles';
</style>
